language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - cpanm -n Devel::Cover::Report::Coveralls
script: perl Build.PL && ./Build build && HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,.*,+select,^lib" prove -lvr t/ xt/
after_success:
  - cover -report coveralls
